#!/usr/bin/sh
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension be5invis.vscode-custom-css
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension geoffkaile.latex-count
code --install-extension higoka.php-cs-fixer
code --install-extension James-Yu.latex-workshop
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension redhat.vscode-yaml
code --install-extension rexshi.phpdoc-comment-vscode-plugin
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-spanish
code --install-extension suntobright.vscode-sftp
code --install-extension vscodevim.vim
code --install-extension whizkydee.material-palenight-theme
code --install-extension yzhang.markdown-all-in-one